_target_: lerobot.common.robot_devices.robots.manipulator.ManipulatorRobot
robot_type: aloha
calibration_dir: .cache/calibration/aloha_default
max_relative_target: null

leader_arms:
  right:
    _target_: lerobot.common.robot_devices.motors.dynamixel.DynamixelMotorsBus
    port: /dev/ttyDXL_leader
    motors:
      waist: [1, xm430-w350]
      shoulder: [2, xm430-w350]
      shoulder_shadow: [3, xm430-w350]
      elbow: [4, xm430-w350]
      elbow_shadow: [5, xm430-w350]
      forearm_roll: [6, xm430-w350]
      wrist_angle: [7, xm430-w350]
      wrist_rotate: [8, xm430-w350]
      gripper: [9, xm430-w350]

follower_arms:
  right:
    _target_: lerobot.common.robot_devices.motors.dynamixel.DynamixelMotorsBus
    port: /dev/ttyDXL_follower
    motors:
      waist: [1, xm540-w270]
      shoulder: [2, xm540-w270]
      shoulder_shadow: [3, xm540-w270]
      elbow: [4, xm540-w270]
      elbow_shadow: [5, xm540-w270]
      forearm_roll: [6, xm540-w270]
      wrist_angle: [7, xm540-w270]
      wrist_rotate: [8, xm430-w350]
      gripper: [9, xm430-w350]
cameras:
  cam_high:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: /dev/CAM_TOP
    fps: 30
    width: 640
    height: 480
  cam_low:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: /dev/CAM_BOTTOM
    fps: 30
    width: 640
    height: 480
  cam_right_wrist:
    _target_: lerobot.common.robot_devices.cameras.opencv.OpenCVCamera
    camera_index: /dev/CAM_RIGHT_WRIST 
    fps: 30
    width: 640
    height: 480

